### ISSUE TITLE
Automatic js bundle

### ISSUE THREAD

**Issue by ShuP1** [not-fl3/sapp-jsutils#7]
Adding a metadata pointing to `.js` files in sapp plugins would allow build time concatenation of js scripts using only `cargo metadata`, `jq` and `bash`

```toml
[package.metadata.sapp]
plugins = ["js/gl.js"]
```
